### ISSUE TITLE
Does this works with v9 getServerSideProps 

### ISSUE THREAD

**Issue by iamchathu** [tokuda109/next-cookie#148]
Does this library works with `getServerSideProps` rather than `getInitialProps`?

**Comment by tokuda109** [comment]
@iamchathu 
I'll get on it!

**Comment by tokuda109** [comment]
@iamchathu 
I'll create sample code to make sure it works.

**Comment by tokuda109** [comment]
@iamchathu 

I fixed it with a pull request [here](https://github.com/tokuda109/next-cookie/pull/152).
It is now available as version 2.4.0.

**Comment by iamchathu** [comment]
@tokuda109 Wow. I will upgrade and use. Thanks you very much
