### ISSUE TITLE
useCookie should also accept GetServerSidePropsContext

### ISSUE THREAD

**Issue by sanchopancho13** [tokuda109/next-cookie#224]
useCookies works inside getServerSideProps, but the context parameter is not NextPageContext.  It is GetServerSidePropsContext.

https://github.com/tokuda109/next-cookie/blob/06f6c29850bd33860ad5d3ca1dd624db9b92a3df/src/useCookie.ts#L4

Change the above signature to accept `ctxOrCookie?: NextPageContext | GetServerSidePropsContext | string`

**Comment by tokuda109** [comment]
@sanchopancho13 
Certainly!
I will fix it.
