### ISSUE TITLE
Support multiple Set-Cookie in single request cycle

### ISSUE THREAD

**Issue by azamuddin** [tokuda109/next-cookie#4]
## Description 
As a developer, I want to be able to set multiple cookies with different keys in a single request cycle. 

## Current condition 
If I set multiple cookie keys, the first key will be lost. 

example: 
```js
 ctx.cookie.set("first_cookie", "value1", {
       path: "/",
       maxAge: 3600 * 24 * 30  // 1 month
 });

 ctx.cookie.set("second_cookie", "value2", {
       path: "/",
       maxAge: 3600 * 24 * 30  // 1 month
 });

ctx.res.writeHead(302, {Location: "/home"});
ctx.res.end();

```
If I execute above code, only `second_cookie` will be saved in the cookie. 

## Expected behaviour
`next-cookie` has API for storing multiple cookie keys just like original NodeJS `setHeader` API.

## Environment
- nextjs@9.1.4
- node@11.5.0
- next-cookie@2.0.0

**Comment by tokuda109** [comment]
@azamuddin 
I'll fix it. thank you!

**Comment by tokuda109** [comment]
@azamuddin 
Version 2.1.1 is released 😃

**Comment by azamuddin** [comment]
Amaziiing, thank you @tokuda109
